# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
project 'NuevaBanca-ios.xcodeproj'
target 'NuevaBanca-ios' do
    pod 'Firebase/Messaging'
    pod 'Firebase/Analytics'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReachabilitySwift'
end
